FROM docker.io/library/node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:docker

FROM docker.io/library/node:18-alpine
WORKDIR /app
RUN npm init -y && npm install express http-proxy-middleware
COPY --from=build /app/dist ./public
COPY server.js .
EXPOSE 8080
USER 1001
CMD ["node", "server.js"]
